### ISSUE TITLE
Exception ignored in: <bound method Viewer.__del__ of <gym.envs.classic_control.rendering.Viewer object at 0x7fa59323ea58>>

### ISSUE THREAD

**Issue by htpauleta** [gxnk/reinforcement-learning-code#4]
Exception ignored in: <bound method Viewer.__del__ of <gym.envs.classic_control.rendering.Viewer object at 0x7fa59323ea58>>
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/gym/envs/classic_control/rendering.py", line 143, in __del__
  File "/usr/local/lib/python3.5/dist-packages/gym/envs/classic_control/rendering.py", line 62, in close
  File "/usr/local/lib/python3.5/dist-packages/pyglet/window/xlib/__init__.py", line 474, in close
  File "/usr/local/lib/python3.5/dist-packages/pyglet/gl/xlib.py", line 343, in destroy
  File "/usr/local/lib/python3.5/dist-packages/pyglet/gl/base.py", line 333, in destroy
  File "/usr/local/lib/python3.5/dist-packages/pyglet/gl/xlib.py", line 333, in detach
  File "/usr/local/lib/python3.5/dist-packages/pyglet/gl/lib.py", line 96, in errcheck
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 954, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 887, in _find_spec
TypeError: 'NoneType' object is not iterable

**Comment by htpauleta** [comment]
希望能给下解决方案，谢谢！

**Comment by shouhuyngheng** [comment]
我也遇到这样的问题了，不知道如何解决，求解。。。。。。。。。

**Comment by cjing9017** [comment]
> 
> 
> 我也遇到这样的问题了，不知道如何解决，求解。。。。。。。。。

需要将环境关闭，在最后加上
env.close()
